import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "./ThemeProvider";

export const metadata: Metadata = {
  title: "Prince's Portfolio",
  description: "Generated by create next app", 
  icons: {
    icon: "/image.png",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}> <ThemeProvider>{children}</ThemeProvider></body>
    </html>
  );
}

